# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainWindow.ui'
##
## Created by: Qt User Interface Compiler version 6.2.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QFrame, QGroupBox,
    QHBoxLayout, QLCDNumber, QLabel, QMainWindow,
    QMenu, QMenuBar, QProgressBar, QPushButton,
    QSizePolicy, QSlider, QStatusBar, QVBoxLayout,
    QWidget)
import resources_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(620, 620)
        MainWindow.setMinimumSize(QSize(620, 620))
        MainWindow.setMaximumSize(QSize(700, 700))
        icon = QIcon()
        icon.addFile(u":/main_icon.png", QSize(), QIcon.Normal, QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.menu_joySet = QAction(MainWindow)
        self.menu_joySet.setObjectName(u"menu_joySet")
        self.menu_Port = QAction(MainWindow)
        self.menu_Port.setObjectName(u"menu_Port")
        self.menu_exit = QAction(MainWindow)
        self.menu_exit.setObjectName(u"menu_exit")
        self.style_classic = QAction(MainWindow)
        self.style_classic.setObjectName(u"style_classic")
        self.style_dark = QAction(MainWindow)
        self.style_dark.setObjectName(u"style_dark")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.wire_rotSpeed_lcd = QLCDNumber(self.centralwidget)
        self.wire_rotSpeed_lcd.setObjectName(u"wire_rotSpeed_lcd")
        self.wire_rotSpeed_lcd.setGeometry(QRect(420, 80, 161, 51))
        self.cath_speed_lcd = QLCDNumber(self.centralwidget)
        self.cath_speed_lcd.setObjectName(u"cath_speed_lcd")
        self.cath_speed_lcd.setGeometry(QRect(30, 80, 161, 51))
        self.cath_speed_lcd.setSegmentStyle(QLCDNumber.Filled)
        self.cath_speed_lcd.setProperty("value", 0.000000000000000)
        self.wire_speed_lcd = QLCDNumber(self.centralwidget)
        self.wire_speed_lcd.setObjectName(u"wire_speed_lcd")
        self.wire_speed_lcd.setGeometry(QRect(230, 80, 161, 51))
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(230, 60, 101, 16))
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(420, 60, 91, 16))
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(30, 60, 101, 16))
        self.cath_pos_speed_lcd = QLCDNumber(self.centralwidget)
        self.cath_pos_speed_lcd.setObjectName(u"cath_pos_speed_lcd")
        self.cath_pos_speed_lcd.setGeometry(QRect(30, 160, 161, 51))
        self.cath_pos_speed_lcd.setSegmentStyle(QLCDNumber.Filled)
        self.cath_pos_speed_lcd.setProperty("value", 0.000000000000000)
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(30, 140, 101, 16))
        self.wire_pos_lcd = QLCDNumber(self.centralwidget)
        self.wire_pos_lcd.setObjectName(u"wire_pos_lcd")
        self.wire_pos_lcd.setGeometry(QRect(230, 160, 161, 51))
        self.wire_pos_lcd.setSegmentStyle(QLCDNumber.Filled)
        self.wire_pos_lcd.setProperty("value", 0.000000000000000)
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(230, 140, 101, 16))
        self.wire_rotPos_lcd = QLCDNumber(self.centralwidget)
        self.wire_rotPos_lcd.setObjectName(u"wire_rotPos_lcd")
        self.wire_rotPos_lcd.setGeometry(QRect(420, 160, 161, 51))
        self.wire_rotPos_lcd.setSegmentStyle(QLCDNumber.Filled)
        self.wire_rotPos_lcd.setProperty("value", 0.000000000000000)
        self.label_8 = QLabel(self.centralwidget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(420, 140, 101, 16))
        self.stroke_progress = QProgressBar(self.centralwidget)
        self.stroke_progress.setObjectName(u"stroke_progress")
        self.stroke_progress.setGeometry(QRect(30, 250, 161, 23))
        self.stroke_progress.setValue(24)
        self.stroke_progress.setTextVisible(False)
        self.line = QFrame(self.centralwidget)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(210, 50, 20, 501))
        self.line.setFrameShape(QFrame.VLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.label_9 = QLabel(self.centralwidget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(30, 230, 101, 16))
        self.cath_up_button = QPushButton(self.centralwidget)
        self.cath_up_button.setObjectName(u"cath_up_button")
        self.cath_up_button.setGeometry(QRect(60, 280, 91, 81))
        self.cath_up_button.setCursor(QCursor(Qt.PointingHandCursor))
        self.cath_up_button.setStyleSheet(u"border-image: url(:/up.png);\n"
"")
        self.cath_down_button = QPushButton(self.centralwidget)
        self.cath_down_button.setObjectName(u"cath_down_button")
        self.cath_down_button.setGeometry(QRect(60, 390, 91, 81))
        self.cath_down_button.setCursor(QCursor(Qt.PointingHandCursor))
        self.cath_down_button.setStyleSheet(u"border-image: url(:/down.png);")
        self.wire_up_button = QPushButton(self.centralwidget)
        self.wire_up_button.setObjectName(u"wire_up_button")
        self.wire_up_button.setGeometry(QRect(260, 280, 91, 81))
        self.wire_up_button.setCursor(QCursor(Qt.PointingHandCursor))
        self.wire_up_button.setStyleSheet(u"\n"
"border-image: url(:/up.png);")
        self.wire_down_button = QPushButton(self.centralwidget)
        self.wire_down_button.setObjectName(u"wire_down_button")
        self.wire_down_button.setGeometry(QRect(260, 390, 91, 81))
        self.wire_down_button.setCursor(QCursor(Qt.PointingHandCursor))
        self.wire_down_button.setStyleSheet(u"border-image: url(:/down.png);")
        self.wire_clock_button = QPushButton(self.centralwidget)
        self.wire_clock_button.setObjectName(u"wire_clock_button")
        self.wire_clock_button.setGeometry(QRect(530, 230, 81, 81))
        self.wire_clock_button.setCursor(QCursor(Qt.PointingHandCursor))
        self.wire_clock_button.setStyleSheet(u"border-image: url(:/clock-wise.png);\n"
"")
        self.wire_antiClock_button = QPushButton(self.centralwidget)
        self.wire_antiClock_button.setObjectName(u"wire_antiClock_button")
        self.wire_antiClock_button.setGeometry(QRect(420, 230, 81, 81))
        self.wire_antiClock_button.setCursor(QCursor(Qt.PointingHandCursor))
        self.wire_antiClock_button.setStyleSheet(u"border-image: url(:/anti-clock-wise.png);")
        self.label_11 = QLabel(self.centralwidget)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(70, 370, 81, 20))
        self.label_12 = QLabel(self.centralwidget)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(270, 370, 81, 20))
        self.label_13 = QLabel(self.centralwidget)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(480, 230, 81, 20))
        self.cath_step_slider = QSlider(self.centralwidget)
        self.cath_step_slider.setObjectName(u"cath_step_slider")
        self.cath_step_slider.setGeometry(QRect(180, 319, 22, 141))
        self.cath_step_slider.setOrientation(Qt.Vertical)
        self.cath_step_slider.setInvertedAppearance(False)
        self.cath_step_slider.setInvertedControls(False)
        self.wire_step_slider = QSlider(self.centralwidget)
        self.wire_step_slider.setObjectName(u"wire_step_slider")
        self.wire_step_slider.setGeometry(QRect(370, 319, 22, 141))
        self.wire_step_slider.setMinimum(0)
        self.wire_step_slider.setValue(0)
        self.wire_step_slider.setOrientation(Qt.Vertical)
        self.wire_step_slider.setInvertedAppearance(False)
        self.wire_step_slider.setInvertedControls(False)
        self.wireRot_step_slider = QSlider(self.centralwidget)
        self.wireRot_step_slider.setObjectName(u"wireRot_step_slider")
        self.wireRot_step_slider.setGeometry(QRect(440, 320, 141, 22))
        self.wireRot_step_slider.setOrientation(Qt.Horizontal)
        self.cath_step_text = QLabel(self.centralwidget)
        self.cath_step_text.setObjectName(u"cath_step_text")
        self.cath_step_text.setGeometry(QRect(150, 470, 61, 20))
        self.wire_step_text = QLabel(self.centralwidget)
        self.wire_step_text.setObjectName(u"wire_step_text")
        self.wire_step_text.setGeometry(QRect(350, 470, 51, 20))
        self.wireRot_step_text = QLabel(self.centralwidget)
        self.wireRot_step_text.setObjectName(u"wireRot_step_text")
        self.wireRot_step_text.setGeometry(QRect(490, 340, 51, 20))
        self.cath_disable_button = QPushButton(self.centralwidget)
        self.cath_disable_button.setObjectName(u"cath_disable_button")
        self.cath_disable_button.setGeometry(QRect(40, 500, 131, 31))
        icon1 = QIcon()
        icon1.addFile(u":/disable.png", QSize(), QIcon.Normal, QIcon.Off)
        self.cath_disable_button.setIcon(icon1)
        self.wire_disable_button = QPushButton(self.centralwidget)
        self.wire_disable_button.setObjectName(u"wire_disable_button")
        self.wire_disable_button.setGeometry(QRect(250, 500, 131, 31))
        self.wire_disable_button.setIcon(icon1)
        self.wire_rot_disable_button = QPushButton(self.centralwidget)
        self.wire_rot_disable_button.setObjectName(u"wire_rot_disable_button")
        self.wire_rot_disable_button.setGeometry(QRect(450, 360, 131, 31))
        self.wire_rot_disable_button.setIcon(icon1)
        self.all_stop_button = QPushButton(self.centralwidget)
        self.all_stop_button.setObjectName(u"all_stop_button")
        self.all_stop_button.setGeometry(QRect(200, 0, 221, 51))
        font = QFont()
        font.setFamilies([u"Agency FB"])
        font.setPointSize(20)
        self.all_stop_button.setFont(font)
        icon2 = QIcon()
        icon2.addFile(u":/stop.png", QSize(), QIcon.Normal, QIcon.Off)
        self.all_stop_button.setIcon(icon2)
        self.all_stop_button.setIconSize(QSize(50, 50))
        self.line_2 = QFrame(self.centralwidget)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(400, 50, 20, 501))
        self.line_2.setFrameShape(QFrame.VLine)
        self.line_2.setFrameShadow(QFrame.Sunken)
        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(420, 400, 181, 171))
        self.verticalLayoutWidget = QWidget(self.groupBox)
        self.verticalLayoutWidget.setObjectName(u"verticalLayoutWidget")
        self.verticalLayoutWidget.setGeometry(QRect(10, 20, 160, 150))
        self.verticalLayout = QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.label = QLabel(self.verticalLayoutWidget)
        self.label.setObjectName(u"label")

        self.verticalLayout.addWidget(self.label)

        self.com_select = QComboBox(self.verticalLayoutWidget)
        self.com_select.addItem("")
        self.com_select.setObjectName(u"com_select")
        self.com_select.setCursor(QCursor(Qt.PointingHandCursor))

        self.verticalLayout.addWidget(self.com_select)

        self.label_2 = QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName(u"label_2")

        self.verticalLayout.addWidget(self.label_2)

        self.joystick_select = QComboBox(self.verticalLayoutWidget)
        self.joystick_select.addItem("")
        self.joystick_select.setObjectName(u"joystick_select")
        self.joystick_select.setCursor(QCursor(Qt.PointingHandCursor))

        self.verticalLayout.addWidget(self.joystick_select)

        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.label_10 = QLabel(self.verticalLayoutWidget)
        self.label_10.setObjectName(u"label_10")

        self.horizontalLayout.addWidget(self.label_10)

        self.label_14 = QLabel(self.verticalLayoutWidget)
        self.label_14.setObjectName(u"label_14")

        self.horizontalLayout.addWidget(self.label_14)


        self.verticalLayout.addLayout(self.horizontalLayout)

        self.gear_level_slider = QSlider(self.verticalLayoutWidget)
        self.gear_level_slider.setObjectName(u"gear_level_slider")
        self.gear_level_slider.setCursor(QCursor(Qt.OpenHandCursor))
        self.gear_level_slider.setMinimum(1)
        self.gear_level_slider.setMaximum(5)
        self.gear_level_slider.setPageStep(1)
        self.gear_level_slider.setValue(1)
        self.gear_level_slider.setOrientation(Qt.Horizontal)

        self.verticalLayout.addWidget(self.gear_level_slider)

        self.cath_mode_select = QComboBox(self.centralwidget)
        self.cath_mode_select.addItem("")
        self.cath_mode_select.addItem("")
        self.cath_mode_select.setObjectName(u"cath_mode_select")
        self.cath_mode_select.setGeometry(QRect(230, 250, 158, 20))
        self.cath_mode_select.setCursor(QCursor(Qt.PointingHandCursor))
        self.label_17 = QLabel(self.centralwidget)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(230, 232, 158, 12))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 620, 23))
        self.menu = QMenu(self.menubar)
        self.menu.setObjectName(u"menu")
        self.menu_2 = QMenu(self.menu)
        self.menu_2.setObjectName(u"menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menu.menuAction())
        self.menu.addAction(self.menu_joySet)
        self.menu.addAction(self.menu_Port)
        self.menu.addSeparator()
        self.menu.addAction(self.menu_2.menuAction())
        self.menu.addSeparator()
        self.menu.addAction(self.menu_exit)
        self.menu_2.addAction(self.style_classic)
        self.menu_2.addAction(self.style_dark)

        self.retranslateUi(MainWindow)
        self.gear_level_slider.valueChanged.connect(self.label_14.setNum)
        self.menu_exit.triggered.connect(MainWindow.close)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"\u624b\u672f\u673a\u5668\u4eba\u4e13\u5bb6", None))
        self.menu_joySet.setText(QCoreApplication.translate("MainWindow", u"\u624b\u67c4\u6620\u5c04\u8bbe\u7f6e", None))
        self.menu_Port.setText(QCoreApplication.translate("MainWindow", u"\u4e32\u53e3\u8c03\u8bd5", None))
        self.menu_exit.setText(QCoreApplication.translate("MainWindow", u"\u9000\u51fa", None))
        self.style_classic.setText(QCoreApplication.translate("MainWindow", u"\u7ecf\u5178", None))
        self.style_dark.setText(QCoreApplication.translate("MainWindow", u"\u6697\u9ed1", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"\u5bfc\u4e1d\u8fdb\u7ed9\u901f\u5ea6", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"\u5bfc\u4e1d\u65cb\u8f6c\u901f\u5ea6", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"\u5bfc\u7ba1\u8fdb\u7ed9\u901f\u5ea6", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"\u5bfc\u7ba1\u5f53\u524d\u4f4d\u7f6e", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"\u5bfc\u4e1d\u5f53\u524d\u4f4d\u7f6e", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"\u5bfc\u4e1d\u5f53\u524d\u89d2\u5ea6", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"\u5bfc\u7ba1\u884c\u7a0b\u4f4d\u7f6e", None))
        self.cath_up_button.setText("")
        self.cath_down_button.setText("")
        self.wire_up_button.setText("")
        self.wire_down_button.setText("")
        self.wire_clock_button.setText("")
        self.wire_antiClock_button.setText("")
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"\u5355\u6b65\u9012\u9001\u6309\u94ae", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"\u5355\u6b65\u9012\u9001\u6309\u94ae", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"\u5355\u6b65\u65cb\u8f6c\u6309\u94ae", None))
        self.cath_step_text.setText(QCoreApplication.translate("MainWindow", u"0.50mm", None))
        self.wire_step_text.setText(QCoreApplication.translate("MainWindow", u"0.50mm", None))
        self.wireRot_step_text.setText(QCoreApplication.translate("MainWindow", u"5.00\u00b0", None))
        self.cath_disable_button.setText(QCoreApplication.translate("MainWindow", u"\u70b9\u6b64\u7981\u6b62\u5bfc\u7ba1\u8fd0\u52a8", None))
        self.wire_disable_button.setText(QCoreApplication.translate("MainWindow", u"\u70b9\u6b64\u7981\u6b62\u5bfc\u4e1d\u9012\u9001", None))
        self.wire_rot_disable_button.setText(QCoreApplication.translate("MainWindow", u"\u70b9\u6b64\u7981\u6b62\u5bfc\u4e1d\u65cb\u8f6c", None))
        self.all_stop_button.setText(QCoreApplication.translate("MainWindow", u"\u673a\u5668\u6025\u505c", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"\u673a\u5668\u4eba\u8bbe\u7f6e", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"\u4e32\u53e3\u9009\u62e9", None))
        self.com_select.setItemText(0, QCoreApplication.translate("MainWindow", u"\u65ad\u5f00\u8fde\u63a5", None))

        self.com_select.setCurrentText(QCoreApplication.translate("MainWindow", u"\u65ad\u5f00\u8fde\u63a5", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"\u624b\u67c4\u9009\u62e9", None))
        self.joystick_select.setItemText(0, QCoreApplication.translate("MainWindow", u"\u65ad\u5f00\u8fde\u63a5", None))

        self.label_10.setText(QCoreApplication.translate("MainWindow", u"\u901f\u5ea6\u6863\u4f4d", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.cath_mode_select.setItemText(0, QCoreApplication.translate("MainWindow", u"\u5bfc\u7ba1\u5e26\u52a8\u5bfc\u4e1d\u8fd0\u52a8", None))
        self.cath_mode_select.setItemText(1, QCoreApplication.translate("MainWindow", u"\u5bfc\u7ba1\u72ec\u7acb\u8fd0\u52a8", None))

        self.label_17.setText(QCoreApplication.translate("MainWindow", u"\u5bfc\u4e1d-\u5bfc\u7ba1\u534f\u540c", None))
        self.menu.setTitle(QCoreApplication.translate("MainWindow", u"\u83dc\u5355", None))
        self.menu_2.setTitle(QCoreApplication.translate("MainWindow", u"\u66f4\u6539\u76ae\u80a4", None))
    # retranslateUi

